import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BottomNavigation } from "@/components/bottom-navigation";
import { TWAProvider } from "@/contexts/twa-context";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-full antialiased`}>
        <main className="h-view-container">
          <TWAProvider>
            {children}
          </TWAProvider>
          <BottomNavigation />
          <Script src="https://telegram.org/js/telegram-web-app.js" />
        </main>
      </body>
    </html>
  );
}
